spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wardRobe
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

knn:
  threshold: 3

  output:
    total: 10
    random:
      ration: 0.4

  input:
    k: 3